name: Secrets and Variables Demo

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      environment:
        description: 'Which environment?'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

env:
  # Repository-level environment variables
  GLOBAL_VAR: "I'm available to all jobs"
  
jobs:
  show-secrets:
    runs-on: ubuntu-latest
    env:
      # Job-level environment variables
      JOB_VAR: "I'm only in this job"
      
    steps:
    - name: Show environment variables
      run: |
        echo "Global var: $GLOBAL_VAR"
        echo "Job var: $JOB_VAR"
        echo "GitHub provided: $GITHUB_REPOSITORY"
        echo "User input: ${{ github.event.inputs.environment }}"
        
    - name: Use secrets (safely)
      env:
        # Secrets should be passed as env vars, not directly in run commands
        SECRET_VALUE: ${{ secrets.SUPER_SECRET }}
        APP_ENVIRONMENT: ${{ vars.APP_ENV }}
      run: |
        echo "Secret is set: $(if [ -n "$SECRET_VALUE" ]; then echo 'YES'; else echo 'NO'; fi)"
        echo "App environment: $APP_ENVIRONMENT"
        # Never do this: echo "Secret: $SECRET_VALUE" (it would be masked but still bad practice)

  conditional-job:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    steps:
    - name: Production only step
      run: echo "This only runs for production!"